- .gitignore
> Test Pull Request

- house-finder-client/src/app/app.component.html
- house-finder-client/src/app/homepage/homepage.component.html
- house-finder-client/src/app/homepage/homepage.component.ts
- house-finder-client/src/app/services/house.service.spec.ts
- house-finder-client/src/app/services/house.service.ts
> [Angular] Home Page - List House

- HouseFinder_API/DataAccess/DTO/HouseDTO.cs
- HouseFinder_API/DataAccess/DTO/MapperProfile.cs
- HouseFinder_API/DataAccess/HouseDAO.cs
- house-finder-client/src/app/models/house.ts
> [API] Home Page - List house

- HouseFinder_API/DataAccess/HouseDAO.cs
- HouseFinder_API/HouseFinder_API/Controllers/HousesController.cs
- HouseFinder_API/Repositories/IRepository/IHousesRepository.cs
- HouseFinder_API/Repositories/Repositories/HouseRepository.cs
> main update house search by name using DTO

- Database.sql
> [Database] Data population

- Database.sql
- HouseFinder_API/DataAccess/DTO/HouseDTO.cs
- HouseFinder_API/DataAccess/HouseDAO.cs
- HouseFinder_API/DataAccess/RoomDAO.cs
- HouseFinder_API/HouseFinder_API/Controllers/HousesController.cs
- house-finder-client/src/app/homepage/homepage.component.html
- house-finder-client/src/app/homepage/homepage.component.ts
- house-finder-client/src/app/models/address.ts
- house-finder-client/src/app/models/house.ts
Display data from API;
Fix bug display front end
> [Angular] Home Page - List House:

- house-finder-client/src/app/Landlord/dashboard/dashboard.component.html
- house-finder-client/src/app/Landlord/dashboard/dashboard.component.spec.ts
- house-finder-client/src/app/Landlord/dashboard/dashboard.component.ts
- house-finder-client/src/app/Landlord/list-room/list-room.component.html
- house-finder-client/src/app/Landlord/list-room/list-room.component.spec.ts
- house-finder-client/src/app/Landlord/list-room/list-room.component.ts
- house-finder-client/src/app/app.module.ts
Generate component dashboard and list room
> [Angular] New component

- HouseFinder_API/DataAccess/DTO/LandlordDasboardInformationDTO.cs
- HouseFinder_API/DataAccess/LandlordInfoDAO.cs
- HouseFinder_API/HouseFinder_API/Controllers/LandLordInfomationController.cs
- house-finder-client/src/app/house-detail/house-detail.component.html
> [API] {Landlord} Dashboard

- house-finder-client/src/index.html
Add Library for Bootstrap Toggle
> [Angular] Libraries

- HouseFinder_API/DataAccess/RoomTypeDAO.cs
- HouseFinder_API/HouseFinder_API/Controllers/RoomTypeController.cs
- HouseFinder_API/HouseFinder_API/Startup.cs
- HouseFinder_API/Repositories/IRepository/IRoomTypeRepository.cs
- HouseFinder_API/Repositories/Repositories/RoomTypeRepository.cs
- house-finder-client/src/app/Landlord/list-room/list-room.component.html
- house-finder-client/src/app/Landlord/list-room/list-room.component.ts
- house-finder-client/src/app/models/roomType.ts
- house-finder-client/src/app/services/room-type.service.ts
> [API] (List Room Type) Remove usage of OData

- house-finder-client/src/app/Guest/room-detail/room-detail.component.html
- house-finder-client/src/app/Guest/room-detail/room-detail.component.spec.ts
- house-finder-client/src/app/Guest/room-detail/room-detail.component.ts
- house-finder-client/src/app/app-routing.module.ts
- house-finder-client/src/app/app.module.ts
> [Angular] (Room Detail)

- house-finder-client/src/app/Landlord/list-room/list-room.component.html
- house-finder-client/src/app/Landlord/list-room/list-room.component.ts
- house-finder-client/src/app/Landlord/update-room/update-room.component.html
- house-finder-client/src/app/Landlord/update-room/update-room.component.ts
> [Angular] List room: Update Room

- house-finder-client/src/app/Guest/homepage/homepage.component.html
- house-finder-client/src/app/Guest/homepage/homepage.component.scss
- house-finder-client/src/app/Guest/house-detail/house-detail.component.html
Filter by Rate: front-end design
> [Angular] (Home Page) Filter OData

- house-finder-client/src/app/Guest/homepage/homepage.component.ts
- house-finder-client/src/app/services/house.service.ts
Filter by Region: pass data to service
> [API] (Home Page) Filter OData 

- HouseFinder_API/DataAccess/DTO/RoomDTO.cs
- HouseFinder_API/DataAccess/HouseDAO.cs
- HouseFinder_API/DataAccess/RoomDAO.cs
- house-finder-client/src/app/Guest/homepage/homepage.component.ts
not select deleted items when query
> [API] (Home Page) Update DAO methods

- Database.sql
- HouseFinder_API/BusinessObjects/FUHouseFinderContext.cs
- HouseFinder_API/BusinessObjects/House.cs
- HouseFinder_API/DataAccess/DTO/AvailableHouseDTO.cs
- HouseFinder_API/DataAccess/DTO/CampusDTO.cs
- HouseFinder_API/DataAccess/DTO/HouseDTO.cs
- house-finder-client/src/app/Guest/homepage/homepage.component.ts
- house-finder-client/src/app/models/campus.ts
- house-finder-client/src/app/services/house.service.ts
> [API + DB] (Home Page) Filter by Distance 

- house-finder-client/src/app/Guest/homepage/homepage.component.ts
- house-finder-client/src/app/services/house.service.ts
> [Angular] (Home Page) Filter by Distance

- house-finder-client/src/app/Common/footer/footer.component.html
- house-finder-client/src/app/Common/footer/footer.component.scss
- house-finder-client/src/app/Common/header/header.component.html
- house-finder-client/src/app/Common/header/header.component.scss
- house-finder-client/src/app/Guest/homepage/homepage.component.html
- house-finder-client/src/app/Guest/homepage/homepage.component.scss
- house-finder-client/src/app/app.component.scss
- house-finder-client/src/styles.scss
> [Angular] (Home Page) House Card Item

- house-finder-client/src/index.html
> {Fix bug} [Angular] Tooltip

- house-finder-client/src/app/Guest/homepage/homepage.component.html
House Card Item: Tooltip in Distance mispositioned
> {Fix bug} [Angular] (Home Page) List House

- HouseFinder_API/HouseFinder.Test/CampusControllerTest.cs
- HouseFinder_API/HouseFinder.Test/HouseFinder.Test.csproj
- HouseFinder_API/HouseFinder_API.sln
> [Test - API] CampusController

- Database.sql
- HouseFinder_API/DataAccess/DTO/HouseDTO.cs
- HouseFinder_API/HouseFinder.Test/HouseControllerTest.cs
- HouseFinder_API/HouseFinder.Test/HouseFinder.Test.csproj
- HouseFinder_API/HouseFinder_API/Controllers/HouseController.cs
GetAvailableHouses;
GetHouseById;
UpdateHouse
> [Test API] HouseController

- house-finder-client/package-lock.json
- house-finder-client/src/app/Guest/homepage/homepage.component.ts
> {Fix bug} [Home Page]

- HouseFinder_API/HouseFinder_API/Controllers/ReportController.cs
- house-finder-client/src/app/Guest/create-order/create-order.component.ts
- house-finder-client/src/app/Guest/house-detail/house-detail.component.ts
> [Angular] Send Report

- house-finder-client/src/app/Guest/create-order/create-order.component.ts
- house-finder-client/src/app/Guest/house-detail/house-detail.component.ts
> [Angular] Send Report, Create Order

- HouseFinder_API/HouseFinder_API/Controllers/OrderController.cs
- HouseFinder_API/HouseFinder_API/Controllers/ReportController.cs
- HouseFinder_API/HouseFinder_API/Controllers/RoomController.cs
- house-finder-client/src/app/Landlord/dashboard/dashboard.component.ts
- house-finder-client/src/app/Landlord/update-room/update-room.component.html
- house-finder-client/src/app/Landlord/update-room/update-room.component.ts
- Alert for Room CRUD
- Landlord list house by landlord id (When login)
> [Hoàn thiện CRUD HOUSE-ROOM]

- HouseFinder_API/DataAccess/UserDAO.cs
> [API] Staff/list-landlord-signup-request #534

- house-finder-client/src/app/Admin/list-staff/list-staff.component.html
- house-finder-client/src/app/Admin/list-staff/list-staff.component.scss
- house-finder-client/src/app/Landlord/dashboard/dashboard.component.html
- house-finder-client/src/app/Landlord/dashboard/dashboard.component.scss
> [Design Front-end] No case data

- house-finder-client/src/app/Guest/create-order/create-order.component.ts
- house-finder-client/src/app/Guest/house-detail/house-detail.component.ts
> [Angular] House Detail

- HouseFinder_API/HouseFinder_API/Controllers/UserController.cs
- house-finder-client/src/app/Guest/login/login.component.html
- house-finder-client/src/app/Guest/login/login.component.ts
> [Angular] (Login)

- house-finder-client/src/app/Guest/homepage/homepage.component.html
- house-finder-client/src/app/Guest/homepage/homepage.component.ts
- house-finder-client/src/app/Guest/house-detail/house-detail.component.html
- house-finder-client/src/app/Guest/house-detail/house-detail.component.ts
> [Angular] (Home Page)

- HouseFinder_API/HouseFinder_API/Controllers/RateController.cs
- house-finder-client/src/app/Guest/house-detail/house-detail.component.html
- house-finder-client/src/app/Guest/house-detail/house-detail.component.ts
> [Angular] (House Detail) Review & Finish
